import numpy as np
import pylab

pylab.figure(figsize=(17,9))
t = np.arange(0, 1000, 1)

pylab.subplot (2, 8, 1)
sig1 = np.sin(2*np.pi*t/1000)
pylab.plot(t, sig1)
pylab.grid('minor')
pylab.title("Signal 1Hz")
pylab.xlabel("Time (мс)")
pylab.subplot (2, 8, 9)
fft_sig1 = np.fft.rfft(sig1)
abs_fft_sig1 = np.abs(fft_sig1)
frequency = np.linspace(0, 1000/2, len(abs_fft_sig1))
pylab.plot(frequency[:11], abs_fft_sig1[:11])
pylab.grid('minor')
pylab.title("Spectre of signal, frequency 1 Hz")
pylab.xlabel("freq")

pylab.subplot (2, 8, 3)
sig2 = np.sin(2*np.pi*2*t/1000)
pylab.plot(t, sig2)
pylab.grid('minor')
pylab.title("Signal 2 Hz")
pylab.xlabel("Time (мс)")
pylab.subplot (2, 8, 11)
fft_sig2 = np.fft.rfft(sig2)
abs_fft_sig2 = np.abs(fft_sig2)
pylab.plot(frequency[:11], abs_fft_sig2[:11])
pylab.grid('minor')
pylab.title("Spectre of signal, frequency 2 Hz")
pylab.xlabel("freq")

pylab.subplot (2, 8, 5)
sig4 = np.sin(2*np.pi*4*t/1000)
pylab.plot(t, sig4)
pylab.grid('minor')
pylab.title("Signal 4 Hz")
pylab.xlabel("Time (мс)")
pylab.subplot (2, 8, 13)
fft_sig4 = np.fft.rfft(sig4)
abs_fft_sig4 = np.abs(fft_sig4)
pylab.plot(frequency[:11], abs_fft_sig4[:11])
pylab.grid('minor')
pylab.title("Spectre of signal, frequency 4 Hz")
pylab.xlabel("freq")

pylab.subplot (2, 8, 7)
sig8= np.sin(2*np.pi*8*t/1000)
pylab.plot(t, sig8)
pylab.grid('minor')
pylab.title("Signal 8 Hz")
pylab.xlabel("Time (мс)")
pylab.subplot (2, 8, 15)
fft_sig8 = np.fft.rfft(sig8)
abs_fft_sig8 = np.abs(fft_sig8)
pylab.plot(frequency[:11], abs_fft_sig8[:11])
pylab.grid('minor')
pylab.title("Spectre of signal, frequency 8 Hz")
pylab.xlabel("freq")
pylab.show()

